### ISSUE TITLE
Api calls returning error message, invalid literal for int()

### ISSUE THREAD

**Issue by cspropertygroup** [django-notifications/django-notifications#257]
ValueError at /inbox/notifications/api/unread_list/
invalid literal for int() with base 10: '<property object at 0x10b692d18>'

**Comment by knasti** [comment]
I am getting the same error, it comes with when making a GET request to: "inbox/notifications/api/unread_list/?max=5". And if I'm correct the error is started at line 172 in notifications/views.py.

I suspect that it might be caused by myself, but if anyone can pinpoint why it happens, I'll be glad :)
