### ISSUE TITLE
Deleting doesn't do anything

### ISSUE THREAD

**Issue by LegoStormtroopr** [django-notifications/django-notifications#52]
I'm having issues with an unrelated bug and was going back over some code changes and it seems that the delete view was changed to use a delete flag https://github.com/django-notifications/django-notifications/commit/f351e92223bdba05e8c71c4a6e16333ab69bb832 , however the querysets don't actually filter these out. So a notification is flagged as deleted, but still appears (I think).

@zhang-z obviously included and recommended this change for a reason, so their input would be handy.

But there are a few proposals I can think of:

1. Revert to use djangos `delete`, have user rely on third party libraries to manage recovery
 * Pros: Notifications are low information so deleting won't lose info
 * Cons: Relies on third-party apps
2. Override `all` queryset so deleted notifications are hidden, add `deleted` queryset to access, posibly even a 'trash' view for recovering/permanently deleting notifications
 * Pros: Self-contained management of deletes, easier/safer for users, more "professional" approach
 * Cons: (minimal) feature bloat, minor additional effort to make new screens.

Each has their benefits and drawbacks, so thoughts would be handy. Its a small piece of work either way and I can find some time to fix it up, but it is worth investigating before a 0.6.3 release.

**Comment by zhang-z** [comment]
Thank you for pointing out the bug. I added the "deleted" field, mainly for these reasons:

1. in many scenarios, it's a common DB design to mark 'deleted' rather than deleting records from DB, for potential (internal) reference in future or avoid inconsistency 

2. for Notifications, consider this case: an event happens to a user --> notification sent out --> user read and delete the notice --> the same event happen again. Then, some applications may want to avoid sending a same notice again. In this case, 'deleted' flag is a must

3. another case: an event occur --> notice sent --> the event disappears --> then the notice should become invalid/deleted --> some time later, the event occurs again, should re-validate/re-create the notice. In this case, I prefer not to deleting & re-creating a same notice. Instead, mark & unmark its 'deleted' field

Back to the bug. What about this solution: add an option 'hard/soft delete' to the delete notification view. By default, it is 'hard delete', which means deleting records from DB. For applications where 'deleted' field is wanted, developers need to explicitly manage the 'soft delete' and query filter.

I will fix it after we consolidate the solution.

**Comment by LegoStormtroopr** [comment]
Yeah, thats why I was reluctant to say rollback completely. Everything you've said sounds great.

I like the hard/soft delete idea. Perhaps through a django setting, in the users `settings.py`, like:

    DJANGO_NOTIFICATIONS_HARD_DELETE = False

**Comment by zhang-z** [comment]
@LegoStormtroopr , I committed the fix. But as I'm not familiar with Travis-ci, seems I was working in a wrong workflow (directly committed to master branch), which didn't trigger Travis-ci's action. Would you be able to help with this commit? I will pickup Travis-ci and create branches in future

**Comment by LegoStormtroopr** [comment]
That was quick, thanks for that Zhang! Ok, I've added myself to the Authors to nudge travis in a pull request.

In future, I'd suggest working on a repository under your own account - either master or a branch.
So if you catch up your fork here: https://github.com/zhang-z/django-notifications you can use that for all your work, and then issue pull requests from your repository into this one. The only tricky thing is making sure your repository stays up to date with the upstream one (i.e. this one).

Here is an article that can help you with this: https://help.github.com/articles/syncing-a-fork/

Let me know if I can help anymore :)

**Comment by zhang-z** [comment]
Awesome! Noted with thanks!

**Comment by yangyubo** [comment]
Great, thank you guys. I'm gonna to name the upcoming release 0.7 (other then 0.6.3), since there are lot of improvements after latest release.
