### ISSUE TITLE
what makes this project different from django-activity-streams?

### ISSUE THREAD

**Issue by justquick** [django-notifications/django-notifications#64]
im confused why my django-activity-streams project was copied and then modified. what makes this app different? could you possibly help modify django-activity-streams to suit your needs? are there any fixes that you could please add to django-activity-streams that are common to both projects? im working to solve this in my project but it seems that this one fixed it already

justquick/django-activity-stream#244
django-notifications/django-notifications#63

**Comment by yangyubo** [comment]
@justquick , thank you for considering the possibility that merging the projects.

The major difference between `django-notifications` and `django-activity-streams` was stated in README.rst of `django-notifications` repo.

I'm not quite sure the current functionalities that `django-activity-streams` provides, but by the time I create `django-notifications`, `django-activity-streams` does not support sending notifications to specific user.

`django-activity-streams` enables users "subscribe" other users status update stream, just like Twitter / Facebook timeline.

On the other side, `django-notifications` try to implement a "push" behavior, this not the same thing.

Take Github as an example, you can see a list of updates that generated by the person you followed, and repos you watched or you owned, `django-activity-streams` does a great job on this use case.

But what if another user "@" you in a commenting thread? What if someone reply you on a repos which you didn't even watch it? You deserved to get a notification instead of a normal updates, since you ether didn't follow that person, nor watch the repos. That's exactly the Github's Notification functionality.

I hope this explains, and please correct me if I misunderstood `django-activity-streams` functionalities.

**Comment by justquick** [comment]
interesting use case, that's exactly how things should work. i think your implementation is pretty complete and i like the read an deleted fields. if i had to implement this i would put those fields on a separate model that represents the notification content itself (kind of like django.contrib.comments) and just use django-activity-stream for managing the actions and following relationships. i think it could look something like this:

```python
class Notification(Model):
    text = TextField()
    read = BooleanField()
    deleted = BooleanField()

notification = Notification.objects.create(...)
sender = User.objects.create(...)
recipient = User.objects.create(...)

action.send(actor=sender, target=recipient, action_object=notification)
```

then you can create a [custom stream](https://django-activity-stream.readthedocs.org/en/latest/streams.html?highlight=custom#writing-custom-streams) that would would return a list of Actions filtered based on the Notification's fields:

```python
class NotificationManager(ActionManager):

    @stream
    def sent_notifications(self, sender, recipient=None):
        filters = {'action_object__read': False, 'action_object__deleted': False}
        if recipient:  # optional recipient
            filters['target'] = recipient
        return sender.actor_actions.filter(**filters)
```

the custom streams work is new since you first started working on this app and it's a great way to access and filter data on separate models

**Comment by honestbleeps** [comment]
I'm actually interested in the functionality of both - having a notification system and having "following"-type features...

Since you're in communication with each other (or at least were, briefly) -- have either of you tried running both of these side by side to see if/how they can complement each other? Has development on that continued at all?

**Comment by zmrenwu** [comment]
I aggree @justquick . In my opinion, the actor and target object in django-notifications model is a little redundant. We can use the method mentioned above by @justquick implement the same thing. There only need a 'involved object' in Notification model. For example, Jack(actor) commented(verb) your(target) post(involved object) 2 days ago. But other views such as mark_as_read, mark as_unread are very useful. So I suggest refactor this app based on django-activity-stream. To more specific, the Notification model would like:
```
class Notification(Model):
    text = TextField()
    read = BooleanField()
    deleted = BooleanField()
    involved_object = (Use generic foreignkey to relate to any django model)
```
