### ISSUE TITLE
Attempting to go to /inbox/notifications/mark-as-read/1234/ throws a 404 error when logged in as another user

### ISSUE THREAD

**Issue by awidgery** [django-notifications/django-notifications#65]
This behaviour seems unexpected.

Attempting to go to e.g. `/inbox/notifications/mark-as-read/111091/` when logged in as a user that doesn't own notification `111091` gives a plain 404 error, rather than a login screen.

Shouldn't it either:
a) log the user out and show a login screen, or
b) show a "you don't have permission to view this page"?

**Comment by zhang-z** [comment]
Hi awidgery, I would see this behaviour as expected.

Regarding choice a) "log the user out and show a login screen", I think a user accidently (program bug, or malicious user) open an inbox message beloning to others does not necessarily mean he/she wants to logout and switch account. Actually this should not happen in normal case. So websites better not to automatically perform a logout.

Regarding choice b), I agree it makes more sense to show "you don't have permission", probably with status code 403. One reason of using 404 is to avoid disclosing too much information to users -- no need to let them know this message ID exist or not, because they're not supposed to access it anyway. You can check out more discussion on this topic at:
https://github.com/tomchristie/django-rest-framework/issues/1439
http://lockmedown.com/when-should-you-return-404-instead-of-403-http-status-code/
http://programmers.stackexchange.com/questions/82371/should-mvc-rest-return-a-403-or-404-for-resources-belonging-to-other-users
http://www.bennadel.com/blog/2400-handling-forbidden-restful-requests-401-vs-403-vs-404.htm

So I personally a bit prefer 404 over 403 in this case.

**Comment by awidgery** [comment]
I can see the point there.
The difficulty is that in a situation where someone has multiple accounts and are logged into e.g. account 1 they will receive an email to the email registered at account 2, and will then receive a 404 with no explanation. Users will simply think the website is broken.

I feel that django-notifications would be improved if there was at least an option for this behaviour, especially for the use of e.g. consumer sites where security vs convenience trade-off leans more towards convenience.

**Comment by zhang-z** [comment]
Agree. That's a reasonable scenario to trigger this 404 page.

I think the most user-friendly solution may be to append a login-token in the URL links that emailed to users. Then when they open the link, the website would be able to handle account-switch correctly, without any extra action from users.

**Comment by awidgery** [comment]
Yes this is a good solution.  Do you think this should be done in the django-notifications library or handled  separately with a middleware?

**Comment by zhang-z** [comment]
In my opinion, the user account management (switch account based on token) should be handled by project, cause the feature is unrelated with 'notification', and could be quite project-specific.

As you said, middleware sounds like a good way to do it.
